name: Upload wfc.log from VM

on:
  workflow_dispatch:
    inputs:
      vm_ip:
        description: 'Public IP address of the VM (e.g. 34.122.100.23)'
        required: true
        type: string
      log_path:
        description: 'Full path to the log file on the VM (e.g. /home/user/logs/wfc.log)'
        required: true
        type: string

jobs:
  fetch-log-and-upload:
    name: Fetch log from VM and upload
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: 🧰 Install SSH client
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client

    - name: 🔑 Prepare SSH and test connection
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        set -e
        echo "🔐 Setting up SSH..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        printf "%s\n" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        echo "🚀 Starting SSH agent"
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

        echo "🧾 Adding VM to known_hosts..."
        ssh-keyscan -T 10 -H ${{ inputs.vm_ip }} >> ~/.ssh/known_hosts || {
          echo "⚠️ Warning: ssh-keyscan failed. Continuing anyway..."
        }

        echo "🔍 Testing SSH connectivity to ${{ inputs.vm_ip }}..."
        ssh -q -o BatchMode=yes -o ConnectTimeout=10 \
          kk_lab_user_794536@${{ inputs.vm_ip }} "echo ✅ SSH connection successful" || {
          echo "❌ SSH connection failed. Check if the VM is online and SSH port is open."
          exit 1
        }

    - name: 📡 Fetch log from VM
      run: |
        echo "📡 Fetching log file from: ${{ inputs.log_path }}"
        ssh -o StrictHostKeyChecking=yes kk_lab_user_794536@${{ inputs.vm_ip }} \
          "cat '${{ inputs.log_path }}'" > wfc.log
        echo "✅ First few lines of fetched log:"
        head -n 10 wfc.log || echo "(file empty)"

    - name: ✅ Verify that log file exists and is not empty
      run: |
        if [[ ! -s wfc.log ]]; then
          echo "❌ Log file is empty or missing!"
          exit 1
        fi

    - name: 📤 Upload wfc.log as artifact
      uses: actions/upload-artifact@v4
      with:
        name: wfc-log
        path: wfc.log
